//Amount of money generated by one money tile-resource
const double TILE_MONEY_RATE = 75.0;

//Amount of energy generated by one energy tile-resource per second
const double TILE_ENERGY_RATE = 0.5;

//Amount of research progress points generated by one
//research tile-resource per second
const double TILE_RESEARCH_RATE = 0.75;

//Amount of labor generation per second by one labor tile-resource
const double TILE_LABOR_RATE = 1.0 / 60.0;
const double LABOR_ACHIEVE_THRESH = 200.0 * TILE_LABOR_RATE;

//Labor's worth of support ships to build per minute with defense
const double DEFENSE_LABOR_PM = 2.0;

//The RTS economy reports production in a readable 60-second cycle while the
//engine accrues it continuously. Values inherited from the old turn-based
//prototype are converted to rates using this duration.
const double ECONOMY_CYCLE_SECONDS = 60.0;
const double ENERGY_RESOURCE_PER_CYCLE = TILE_ENERGY_RATE * ECONOMY_CYCLE_SECONDS;

//Single source of truth for the opening RTS stockpile. Keeping this named and
//covered by a data-contract test prevents the old 50-versus-500 regression.
const int STARTING_MINERALS = 50;

//Compatibility alias for older scripts/data comments.
const double TURN_LENGTH = ECONOMY_CYCLE_SECONDS;
